/**
 * Front Office API
 * # Front Office The front office is typically used within front-end apps, for example a website or a mobile application. With this SDK, you can handle interactions with documents and request a list of personalized documents.  ## User Each method requires a `user_id`. From our perspective, a `user_id` is simply required to group interactions together. We don't need to know who that user is, so it is preferred to create this `user_id` in a privacy-preserving way. For example, create a hash method which transforms your user into an ID hash.  ## Document A document here is represented by its `id` and optional `properties`. In order to display a document in an interface, it's preferred to use `properties`, which is an arbitrary collection of values. For example, it could contain an image url, a full article url, the publication date, the author or much more. The properties that were added when the document was submitted to us, are just mirrored here.  ## Auth The API requires an authenticationToken when used. Please see further down in this README.md file, or refer to the test included in this SDK's codebase, on how to set this token correctly. \\
 *
 * The version of the OpenAPI document: 1.0.0-rc10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InputUser from './InputUser';

/**
 * The SemanticSearchRequestPersonalize model module.
 * @module model/SemanticSearchRequestPersonalize
 * @version 1.0.27
 */
class SemanticSearchRequestPersonalize {
    /**
     * Constructs a new <code>SemanticSearchRequestPersonalize</code>.
     * Personalize the ranking of candidates based on a users preferences
     * @alias module:model/SemanticSearchRequestPersonalize
     * @param user {module:model/InputUser} 
     */
    constructor(user) { 
        
        SemanticSearchRequestPersonalize.initialize(this, user);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, user) { 
        obj['user'] = user;
    }

    /**
     * Constructs a <code>SemanticSearchRequestPersonalize</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SemanticSearchRequestPersonalize} obj Optional instance to populate.
     * @return {module:model/SemanticSearchRequestPersonalize} The populated <code>SemanticSearchRequestPersonalize</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SemanticSearchRequestPersonalize();

            if (data.hasOwnProperty('exclude_seen')) {
                obj['exclude_seen'] = ApiClient.convertToType(data['exclude_seen'], 'Boolean');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = InputUser.constructFromObject(data['user']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SemanticSearchRequestPersonalize</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SemanticSearchRequestPersonalize</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SemanticSearchRequestPersonalize.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `user`
        if (data['user']) { // data not null
          InputUser.validateJSON(data['user']);
        }

        return true;
    }


}

SemanticSearchRequestPersonalize.RequiredProperties = ["user"];

/**
 * If true do not include documents the user has already seen as search candidate.  A trimmed version of the users history might be used for this filter.  This option is incompatible with not specifying a user. 
 * @member {Boolean} exclude_seen
 * @default true
 */
SemanticSearchRequestPersonalize.prototype['exclude_seen'] = true;

/**
 * @member {module:model/InputUser} user
 */
SemanticSearchRequestPersonalize.prototype['user'] = undefined;






export default SemanticSearchRequestPersonalize;

